### ISSUE TITLE
怎么我搭建的博客不显示内容？

### ISSUE THREAD

**Issue by briteming** [m4xshen/github-issue-blog#13]
hi.
按照你的程序，我搭建了博客https://gib-swart.vercel.app/ ，不过我搭建的博客不显示内容，为什么？
如何修复？

我在此：https://github.com/briteming/gib/issues/1 提交了一个issue.

**Comment by m4xshen** [comment]
Hi @briteming 感謝你嘗試，確認幾個問題

1. 在 local 也顯示不了嗎？
2. environment.d.ts 裡面的 environment variable 是否都有設定了？

**Comment by briteming** [comment]
clone 到本地电脑也不行：
12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ nano environment.d.ts

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ pnpm build

> github-issue-blog@0.1.0 build C:\Users\12799\gib
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./environment.d.ts:7:22
Type error: ';' expected.

   5 |     GITHUB_CLIENT_SECRET: a-string;
   6 |     AUTHOR_NAME: brite;
>  7 |     BLOG_TITLE: blog of brite;
     |                      ^
   8 |     BLOG_DESCRIPTION: it is blog of brite;
   9 |     NEXT_PUBLIC_OWNER: briteming;
  10 |     NEXT_PUBLIC_REPO: gib;
 ELIFECYCLE  Command failed with exit code 1.

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$

不明白“./environment.d.ts:7:22
Type error: ';' expected ” 是什么意思？

**Comment by briteming** [comment]
我修改了environment.d.ts文件，然后push到vercel, vercel的console log也显示：
<img width="949" alt="105735" src="https://github.com/user-attachments/assets/bcd8af36-2379-4e69-a7ca-16fb10389df7">

不知如何解决？

**Comment by briteming** [comment]
另外，编辑environment.d.ts ，把client secret的值写出来在repo里，这安全吗

**Comment by m4xshen** [comment]
@briteming 不是寫在 `environment.d.ts`，而是要寫在 `.env.local` 中，這樣就不會被 `git commit` 進去。`environment.d.ts` 只是告訴你有哪些 environment variable 需要設置

範例 `.env.local`:
```
GITHUB_CLIENT_ID="00000000000000000000"
GITHUB_CLIENT_SECRET="0000000000000000000000000000000000000000"
AUTHOR_NAME="Daniel"
BLOG_TITLE="Daniel's Blog"
BLOG_DESCRIPTION="Hi, I'm Daniel, a software engineer from Taiwan. Welcome to my blog!"
NEXT_PUBLIC_OWNER="m4xshen"
NEXT_PUBLIC_REPO="example-blog"
```

如果以上設置在 local 可行的話，在 Vercel 上可以依照這個教學設置 environment variable: https://vercel.com/docs/projects/environment-variables

btw 如果你已經 push 你的 environment variable 到 GitHub 上，建議重新生成一組，原本的那組就不安全了

**Comment by briteming** [comment]
hi.

我在clone下来的仓库里，新建了.env.local文件，并填入了相关参数。然后，
12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ ls
README.md         next-env.d.ts    node_modules/  playwright.config.ts  postcss.config.js  tailwind.config.ts  tsconfig.json
environment.d.ts  next.config.mjs  package.json   pnpm-lock.yaml        src/               tests/              yarn.lock

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ rm -rf node_modules/

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ yarn
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
warning tailwind-variants@0.1.20: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning "@nextui-org/react > @nextui-org/badge > @nextui-org/system-rsc@2.0.11" has unmet peer dependency "tailwind-variants@>=0.1.13".
[4/4] Building fresh packages...
Done in 138.94s.

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ ls
README.md         next-env.d.ts    node_modules/  playwright.config.ts  postcss.config.js  tailwind.config.ts  tsconfig.json
environment.d.ts  next.config.mjs  package.json   pnpm-lock.yaml        src/               tests/              yarn.lock

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ yarn build
yarn run v1.22.22
$ next build
   ▲ Next.js 14.1.0
   - Environments: .env.local

   Creating an optimized production build ...
(node:30460) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:25276) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
(node:25276) ExperimentalWarning: CommonJS module C:\Users\12799\gib\node_modules\tailwindcss\lib\lib\load-config.js is loading ES Module C:\Users\12799\gib\tailwind.config.ts using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 ✓ Compiled successfully

./src/components/Layout/ToasterWrapper.tsx
25:6  Warning: React Hook useEffect has missing dependencies: 'pathname' and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
   Collecting page data  .(node:30928) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "..\package.json")
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Collecting page data
   Generating static pages (4/7)  [==  ]
(node:14596) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ λ /                                    55.3 kB         351 kB
├ λ /_not-found                          879 B          85.1 kB
├ λ /auth/callback                       0 B                0 B
├ λ /post/[number]                       1.37 kB         305 kB
├ λ /post/edit/[number]                  820 B           160 kB
└ λ /post/new                            820 B           160 kB
+ First Load JS shared by all            84.2 kB
  ├ chunks/69-b1eed56a4118f8a6.js        28.9 kB
  ├ chunks/fd9d1056-a85eaffd1f8540c0.js  53.4 kB
  └ other shared chunks (total)          1.97 kB


λ  (Dynamic)  server-rendered on demand using Node.js

Done in 67.64s.

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ ls
README.md         next-env.d.ts    node_modules/  playwright.config.ts  postcss.config.js  tailwind.config.ts  tsconfig.json
environment.d.ts  next.config.mjs  package.json   pnpm-lock.yaml        src/               tests/              yarn.lock

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ find . -name index.html
./node_modules/playwright-core/lib/vite/htmlReport/index.html
./node_modules/playwright-core/lib/vite/recorder/index.html
./node_modules/playwright-core/lib/vite/traceViewer/index.html

12799@DESKTOP-B6LK9IO MINGW64 ~/gib (main)
$ ls
README.md         next-env.d.ts    node_modules/  playwright.config.ts  postcss.config.js  tailwind.config.ts  tsconfig.json
environment.d.ts  next.config.mjs  package.json   pnpm-lock.yaml        src/               tests/              yarn.lock

这表示成功了吗？怎么没找到index.html文件？

**Comment by briteming** [comment]
哦，运行：
yarn start

然后，在浏览器里，访问http://localhost:3000 ，果然正常了:
https://i.imgur.com/2o1MBas.png

顺便问下，我在此处https://github.com/m4xshen/github-issue-blog/issues/13#issuecomment-2532628563 上传的图片，你看得见吗？

**Comment by m4xshen** [comment]
> 顺便问下，我在此处https://github.com/m4xshen/github-issue-blog/issues/13#issuecomment-2532628563 上传的图片，你看得见吗？

可以～

**Comment by briteming** [comment]
不过，我push到vercel后，所得网址https://gib-fuk8fz4wl-luckypoems-projects.vercel.app/ 仍然不显示帖子。

**Comment by m4xshen** [comment]
@briteming 在 Vercel 也要設置 environment variable: https://vercel.com/docs/projects/environment-variables

**Comment by briteming** [comment]
<img width="481" alt="170813" src="https://github.com/user-attachments/assets/f3f30e72-d380-43ff-b985-4d9d012b1760" />
hi.
我添加了环境变量,见上图,然后点击deploy按钮,得到的网址是https://gib-yduk.vercel.app/ ,依然不显示帖子,真是奇怪.
谢谢回复!

难道我的环境变量的值填错了?没错的,我核对过了

**Comment by m4xshen** [comment]
只有 open 的 issue 會顯示為文章，看起來你的 repo 目前沒有 open issue

**Comment by briteming** [comment]
你好。
你访问https://github.com/briteming/gib/issues ，3个issue都是open的。你为何说“看起來你的 repo 目前沒有 open issue”？

**Comment by briteming** [comment]
hi.
我新建了 .env 文件：https://github.com/briteming/gib/blob/main/.env ， 这次vercel.com/new的添加environment variables那一步就不用手工添加environment variables了，这一次成功显示帖子了：https://gib-kk.vercel.app/ ，不过仍有1个问题：

非owner用户：luckypoem提交的 issue：https://github.com/briteming/gib/issues/4 也进入我的博客了：https://gib-kk.vercel.app/post/4，怎么解决此问题？我观察了其他的 github issues-based blog程序是通过添加label来解决的。所以你可否考虑实施添加label的机制来阻止非owner用户提交的 issue 进入博客？

**Comment by m4xshen** [comment]
@briteming 

> 我新建了 .env 文件：https://github.com/briteming/gib/blob/main/.env ， 

hmm 但是 `.env` 不應該被 commit 到 git 中才對

> 所以你可否考虑实施添加label的机制来阻止非owner用户提交的 issue 进入博客？

ok, 不過最近有點忙可能要等我有空才能加上這功能，但如果你很急的話也可以自己實作然後發個 PR～
